version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify the Node.js version you need
    commands:
      - npm install -g npm  # Install or update npm globally
      # Add any other installation steps you need (e.g., dependencies, tools)

  build:
    commands:
      # Install Terraform (adjust the version as needed)
      - curl -O https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip
      - unzip terraform_0.14.11_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version  # Verify Terraform installation

      # Initialize Terraform
      - terraform init
      
      # Validate Terraform configuration
      - terraform validate
      
      # Create Terraform plan
      - terraform plan -out=tfplan

      # Apply Terraform plan (auto-approve)
      - terraform apply -auto-approve tfplan

# Add post-build phases if needed (e.g., deployment)

artifacts:
  files:
    - '**/*'  # Include all files in the build output

# Add additional configuration as required
